version: '2'
services:
  web:
    container_name: egg-api
    build: .
    depends_on:
      - db
    ports:
      - '8080:80'
    volumes:
      - .:/project
    environment:
      - DATABASE=host=db user=postgres
  db:
    image: 'postgres:9.6'
