name: egg-api
version: "1.0.0"
executables:
  app:
    main: Main.hs
    source-dirs: src
    dependencies:
      - egg-api
      - aeson
      - base
      - envy
      - wai
      - wai-cors
      - warp
      - http-types
      - postgresql-simple
      - containers
      - mtl
      - text
      - QuickCheck
      - bytestring

library:
  source-dirs: lib
  dependencies:
    - aeson
    - base
    - bytestring
    - containers
    - envy
    - http-types
    - postgresql-simple
    - mtl
    - string-conversions
    - text
    - QuickCheck
    - wai
    - warp
    - generic-arbitrary
  ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  unit-tests:
    main: Main.hs
    source-dirs:
      - test
      - lib
    dependencies:
      - aeson
      - base
      - bytestring
      - containers
      - envy
      - http-types
      - hspec
      - postgresql-simple
      - mtl
      - QuickCheck
      - string-conversions
      - text
      - generic-arbitrary
      - wai
      - warp
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
