name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install libpq-dev
      run: sudo apt-get install libpq-dev
    - name: Run stack build
      run: stack build
    - name: Run stack test
      run: stack test

